let products = [
    {"id": 1001,
    "title":"Cat Food,25lb bag",
    "description":"A 25 pound bag of irresistible organic goodness for your cat",
    "price":2000,
    "image":"images/catfood.png",
    "availableInventory": 10,
    "rating": 3,
},
    {"id": 1002,
    "title":"Yarn",
    "description":"yarn your cat can play with for very long time",
    "price":2.99,
    "image":"images/yarn.jpeg",
    "availableInventory": 20,
    "rating": 4,
},
{"id": 1003,
    "title":"Ball",
    "description":"ball your cat can play with for very long time",
    "price":5.99,
    "image":"images/ball.jpg",
    "availableInventory": 20,
    "rating": 4,
},
{"id": 1004,
    "title":"Litter",
    "description":"Litter where your cat can litter",
    "price":15.99,
    "image":"images/litter.jpg",
    "availableInventory": 5,
    "rating": 2,
},
{"id": 1005,
    "title":"Sand",
    "description":"sand your cat can place it in the litter",
    "price":11.99,
    "image":"images/sandjpeg.jpeg",
    "availableInventory": 15,
    "rating":3,
}
]